services:
  main-service:
    build: main-app/
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
      - payment-service
    environment:
      - SPRING_R2DBC_URL=r2dbc:postgresql://db:5432/intershop
      - SPRING_R2DBC_USERNAME=s
      - SPRING_R2DBC_PASSWORD=sa
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PAYMENT_SERVICE_URL=http://payment-service:9090

  payment-service:
    build: payment-service/
    ports:
      - "9090:9090"

  db:
    image: postgres:13.7-alpine
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_USER=s
      - POSTGRES_PASSWORD=sa
      - POSTGRES_DB=intershop

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"