spring:
  application:
    name: practicum

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/intershop
    username: s
    password: sa

    jpa:
      generate-ddl: true
      hibernate:
        ddl-auto: update
        #ddl-auto: none

      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: true

  sql:
    init:
      mode: always

  main:
    banner-mode: off