spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/intershop
    username: s
    password: sa
    initialization-mode: always

    #application:
    #name: practicum

    #datasource:
      #driverClassName: org.postgresql.Driver


    #jpa:
      # generate-ddl: true
      #  hibernate:
      #    ddl-auto: create
      #    #ddl-auto: none

      # properties:
      #   hibernate:
      #     dialect: org.hibernate.dialect.PostgreSQLDialect
    #     format_sql: true

  sql:
    init:
      mode: always

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  main:
    banner-mode: off

#logging:
  # level:
#    io.r2dbc.postgresql.QUERY: DEBUG # for queries
#    io.r2dbc.postgresql.PARAM: DEBUG # for parameters