spring:
  application:
    name: practicum

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/intershop
    username: s
    password: sa

    #datasource:
    #  driverClassName: org.postgresql.Driver
    #  url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    # username: ${POSTGRES_USER}
    # password: ${POSTGRES_PASSWORD}

    jpa:
      generate-ddl: true
      hibernate:
        ddl-auto: create
        #ddl-auto: none

      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: true

  sql:
    init:
      mode: always

  main:
    banner-mode: off