server: #Сервис платежей (сервер)
  port:   9090

  spring:
    security:
      oauth2:
        resourceserver:
          jwt:
            #issuer-uri: http://localhost:8080/realms/master # Для запуска локально; Адрес сервера авторизации для получения токена
            issuer-uri: http://keycloak:8080/realms/master # Для запуска в Docker
            #host: keycloak
            #port: 8080

    main:
      banner-mode: off

springdoc:
  swagger-ui:
    # Флаг включения UI
    enabled: true
    # Путь UI-части
    path: /swagger-ui-custom.html
    # Флаг включения возможности отправлять запросы из браузера
    tryItOutEnabled: true
    # Флаг включения сохранения авторизации. Если включить, при перезагрузке или закрытии страницы данные авторизации не потеряются
    persistAuthorization: true