server: #Основное приложение (клиент)
  port:   8180

spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/master # Адрес сервера авторизации для получения токена
        registration:
          main-app: # Описание клиента OAuth2
            provider: keycloak
            authorizationGrantType: client_credentials
            client-id: main-app
            client-secret: VmGXQDXNGOZzJH5Mx7Fi4OyHtnb3IH8A
            scope: profile
            clientAuthenticationMethod: client_secret_post # Способ передачи секрета

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/intershop
    username: s
    password: sa
    initialization-mode: always

    #datasource:
      #driverClassName: org.postgresql.Driver

    #jpa:
      # generate-ddl: true
      #  hibernate:
      #    ddl-auto: create
      #    #ddl-auto: none

      # properties:
      #   hibernate:
      #     dialect: org.hibernate.dialect.PostgreSQLDialect
    #     format_sql: true

  sql:
    init:
      mode: always

  data:
    redis:
      host: 127.0.0.1 # Для запуска приложения локально
      #host: redis # Для запуска приложения в Docker
      port: 6379
  cache:
    redis:
      time-to-live: PT5S    # TTL по умолчанию для кешей

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  main:
    allow-bean-definition-overriding: true
    banner-mode: off

    #logging:
  # level:
#    io.r2dbc.postgresql.QUERY: DEBUG # for queries
#    io.r2dbc.postgresql.PARAM: DEBUG # for parameters

  #security:
      #user:
    # name: 1
      # password: 1

payment-service.url: http://localhost:9090